import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "사이트 A",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} 
        antialiased border-2 min-h-screen flex flex-col`}
      >
        <header>
          <nav className="flex gap-4">
            <Link href="/" className="border p-2 rounded">메인</Link>
            <Link href="/posts" className="border p-2 rounded">글 목록</Link>
          </nav>
        </header>
        <main className="flex-1 flex justify-center items-center flex-col">{children}</main>
        <footer>
          푸터
        </footer>
      </body>
    </html>
  );
}